#!/bin/bash

# There's a plugin for this but not sure how to append travis code 

readme=README.md

set -e


dzil build
pod2markdown < Router-Right-*/lib/Router/Right.pm > $readme

cat << EOT >> $readme

[![Build Status](https://travis-ci.org/mla/router-right.svg?branch=master)](https://travis-ci.org/mla/router-right)
EOT
